In [4]:
a=[[11,12,13],[21,22,23],[31,32,33]]
import numpy as np
b=np.array(a)
b

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [6]:
#to show dimension 
b.ndim

2

In [7]:
# To show the shape
b.shape

(3, 3)

In [8]:
# To show the size of array
b.size

9

In [9]:
b[1][2]

23

In [10]:
#slicing
b[0,0:2]

array([11, 12])

In [12]:
#slicing
b[0:2,2]

array([13, 23])

In [13]:
# Import the libraries

import numpy as np 
import matplotlib.pyplot as plt

In [15]:
# Create a list

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [16]:
# Convert list to Numpy Array
# Every element is the same type

A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [17]:
# Show the numpy array dimensions

A.ndim

2

In [18]:
# Show the numpy array shape

A.shape

(3, 3)

In [19]:
# Show the numpy array size

A.size

9

In [20]:
# Access the element on the second row and third column

A[1, 2]

23

In [21]:
# Access the element on the second row and third column

A[1][2]

23

In [22]:
# Access the element on the first row and first column

A[0][0]

11

In [23]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])

In [24]:
# Access the element on the first and second rows and third column

A[0:2, 2]

array([13, 23])

In [25]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [26]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [27]:
# Add X and Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [28]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [29]:
# Multiply Y with 2

Z = 2 * Y
Z

array([[4, 2],
       [2, 4]])

In [30]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
Y

array([[2, 1],
       [1, 2]])

In [31]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
X

array([[1, 0],
       [0, 1]])

In [32]:
# Multiply X with Y

Z = X * Y
Z

array([[2, 0],
       [0, 2]])

In [33]:
# Create a matrix A

A = np.array([[0, 1, 1], [1, 0, 1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [34]:
# Create a matrix B

B = np.array([[1, 1], [1, 1], [-1, 1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [35]:
# Calculate the dot product

Z = np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [36]:
# Calculate the sine of Z

np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [37]:
# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [38]:
# Get the transposed of C

C.T

array([[1, 2, 3],
       [1, 2, 3]])

In [41]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0,1:3]
out


array([0, 1])

In [42]:
X

array([[1, 0, 1],
       [2, 2, 2]])

In [44]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]])
Z=np.dot(X,Y)
Z

array([[2, 2],
       [2, 2]])

In [45]:
X=np.array([[1,0],[0,1]])
Y=np.array([[0,1],[1,0]])
Z=X+Y
Z

array([[1, 1],
       [1, 1]])

In [46]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0:2,2]
out

array([1, 2])

In [47]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]])
Z=np.dot(X,Y)
Z

array([[2, 2],
       [2, 2]])